{{- if .Values.deployment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
      {{- with .Values.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
{{- if or (.Values.enablePodSecurity) (eq (.Values.enablePodSecurity | toString) "<nil>") }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
{{- end }}
      {{- with .Values.initContainers }}
      initContainers: 
{{ toYaml . | indent 6 }}
      {{- end }}
      containers:
        - name: {{ .Values.containername }}
{{- if or (.Values.enablePodSecurity) (eq (.Values.enablePodSecurity | toString) "<nil>") }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
{{- end }}
          image: {{ .Values.image.name }}
          ports:
            - containerPort: {{ .Values.image.containerPort }}
          {{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.probes }}
          probes:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml . | indent 10 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}