{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
    {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if .Values.privateSubnetLB }}
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ .Values.privateSubnetLB}}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if (not .Values.privateSubnetLB) }}
      {{- if .Values.service.loadBalancerIP }}
        {{- $env := .Values.environment }}
        {{- range $environment, $loadBalancerIP := .Values.service.loadBalancerIP }}
          {{- if eq $env $environment }}
  loadBalancerIP: {{ $loadBalancerIP }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- else }}
      {{- if .Values.service.privateSubnetLB_IP }}
        {{- $env := .Values.environment }}
        {{- range $environment, $privateSubnetLB_IP := .Values.service.privateSubnetLB_IP }}
          {{- if eq $env $environment }}
  loadBalancerIP: {{ $privateSubnetLB_IP }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}
{{- end }}